name: noty
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/arutyun88/noty
repository: https://github.com/arutyun88/noty

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
